name: "Hit a webhook"
 
on:
  push:
    tags:
      - '**'
 
jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
    - name: REST API with curl
      run: |
        curl -X GET "https://challenge.uccuhacker.tw/nop.php?token=MzZ8a2RkY28=_f7d663f38bc772b661937cbdd3c4a7656393952c98745bfd5455eb6bc0be09d7"
